# Generated by Django 5.1.5 on 2025-02-01 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuseraccount',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
