# Generated by Django 5.1.5 on 2025-02-14 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuseraccount_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuseraccount',
            name='phone_number',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
