# Generated by Django 5.1.5 on 2025-02-14 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('sku', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryneeded',
            name='sku',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_needed', to='sku.sku'),
        ),
    ]
