# Generated by Django 5.1.5 on 2025-02-14 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payout', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallettransaction',
            old_name='amount',
            new_name='amount_payed',
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='balance_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
            preserve_default=False,
        ),
    ]
