# Generated by Django 5.1.5 on 2025-02-19 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payout', '0002_rename_amount_wallettransaction_amount_payed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallettransaction',
            name='message',
            field=models.TextField(default='-'),
        ),
    ]
