# Generated by Django 5.1.5 on 2025-02-19 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payout', '0003_wallettransaction_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransaction',
            name='message',
            field=models.TextField(),
        ),
    ]
